# -*- coding: utf-8 -*-
"""ResnetT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GnGCgunOxD7-J7k0ngzxGU13zVOLyvD5
"""

import numpy as np
import nibabel as nib
import glob
import os
import random
import tensorflow as tf
#import splitfolders  # or import split_folders
from tensorflow.keras.utils import to_categorical
import seaborn as sns
from tensorflow.keras.applications import EfficientNetB0
import matplotlib.pyplot as plt
from tifffile import imsave
import cv2
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, TensorBoard, ModelCheckpoint
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K
from tensorflow.keras import layers
from tensorflow import keras
from tensorflow.keras.models import Sequential
from sklearn.metrics import classification_report,confusion_matrix
from PIL import Image
from keras.models import load_model
from skimage.color import rgb2gray
from sklearn.utils import shuffle

'''#train HGG
HGG_train_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/train/HGG_t2/*.nii'))
HGG_mask_train_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/train/HGG_masks/*.nii'))
#val HGG
HGG_val_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/val/HGG_t2/*.nii'))
HGG_mask_val_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/val/HGG_masks/*.nii'))
#test HGG
HGG_test_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/test/HGG_t2/*.nii'))
HGG_mask_test_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/test/HGG_masks/*.nii'))

#train LGG
LGG_train_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/train/LGG_t2/*.nii'))
LGG_mask_train_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/train/LGG_masks/*.nii'))
#val LGG
LGG_val_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/val/LGG_t2/*.nii'))
LGG_mask_val_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/val/LGG_masks/*.nii'))
#test LGG
LGG_test_list_t2 = sorted(glob.glob('/content/drive/MyDrive/T2_split/test/LGG_t2/*.nii'))
LGG_mask_test_list = sorted(glob.glob('/content/drive/MyDrive/T2_split/test/LGG_masks/*.nii'))'''

HGG_list_t2 = sorted(glob.glob('/content/drive/MyDrive/TrainT2/HGG_t2/*.nii'))
LGG_list_t2 = sorted(glob.glob('/content/drive/MyDrive/TrainT2/LGG_t2/*.nii'))

len(HGG_list_t2)

len(LGG_list_t2)

HGG = []
LGG = []
for img in range(len(HGG_list_t2)):   #Using t1_list as all lists are of same size   
    temp_image_t2_HGG = nib.load(HGG_list_t2[img]).get_fdata()
    HGG.append(temp_image_t2_HGG)

for img in range(len(LGG_list_t2)):
    temp_image_t2_LGG = nib.load(LGG_list_t2[img]).get_fdata()
    LGG.append(temp_image_t2_LGG)

from sklearn.model_selection import train_test_split
import numpy as np

# Combine the HGG and LGG lists
X = np.array(HGG + LGG)
y = np.array([0] * len(HGG) + [1] * len(LGG))

# Divide the data into train, validation and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1)

# Print the shapes of the train and test sets
print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)
print('X_train shape:', X_val.shape)
print('y_train shape:', y_val.shape)
print('X_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
from torchvision.models import ResNet50_Weights

class MyCustomResnet50(nn.Module):
    def __init__(self, pretrained=True):
        super().__init__()

        # Load the pretrained ResNet50 model
        resnet50 = models.resnet50(pretrained=True)

        # Replace the first convolutional layer to handle images with shape (240, 240, 155)
        resnet50.conv1 = nn.Conv2d(155, 64, kernel_size=7, stride=2, padding=3, bias=False)

        # Reuse the other layers from the pretrained ResNet50 model
        self.features = nn.Sequential(*list(resnet50.children())[:-2])
        self.avgpool = nn.AdaptiveAvgPool2d(output_size=(1, 1))
        self.fc1 = nn.Linear(in_features=2048, out_features=128, bias=True)
        self.fc2 = nn.Linear(128, 2)



    def forward(self, x, dropout = nn.Dropout(p=0.5)
):
        x = self.features(x)
        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        x = dropout(x)
        x = F.relu(self.fc2(x))

        return x

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset
from torch.nn import functional as F

# Define the device to be used for training
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Define the transformation to be applied to the images
transform = transforms.Compose([
    transforms.Resize((240, 240)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

# Convert the train, val and test data to PyTorch tensors
X_train = torch.from_numpy(X_train).float()
y_train = torch.from_numpy(y_train).long()
X_val = torch.from_numpy(X_val).float()
y_val = torch.from_numpy(y_val).long()
X_test = torch.from_numpy(X_test).float()
y_test = torch.from_numpy(y_test).long()

# Define the test dataset
test_dataset = TensorDataset(X_test, y_test)

# Define the dataset
train_dataset = TensorDataset(X_train, y_train)
val_dataset = TensorDataset(X_val, y_val)
test_dataset = TensorDataset(X_test, y_test)

# Define the data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Define the model
model = MyCustomResnet50().to(device)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Define the training loop
def train(model, device, train_loader, criterion, optimizer):
    model.train()
    train_loss = 0
    train_correct = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.permute(0, 3, 1, 2).to(device), target.to(device) # Permute dimensions
        print(data)
        print(target)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        train_loss += loss.item()
        pred = output.argmax(dim=1, keepdim=True)
        train_correct += pred.eq(target.view_as(pred)).sum().item()
        loss.backward()
        optimizer.step()

    train_loss /= len(train_loader.dataset)
    train_accuracy = 100. * train_correct / len(train_loader.dataset)
    return train_loss, train_accuracy

# Define the validating loop
def validation(model, device, val_loader, criterion):
    model.eval()
    val_loss = 0
    val_correct = 0
    with torch.no_grad():
        for data, target in val_loader:
            data, target = data.permute(0, 3, 1, 2).to(device), target.to(device) # Permute dimensions
            output = model(data)
            val_loss += criterion(output, target).item()
            pred = output.argmax(dim=1, keepdim=True)
            val_correct += pred.eq(target.view_as(pred)).sum().item()

    val_loss /= len(val_loader.dataset)
    val_accuracy = 100. * val_correct / len(val_loader.dataset)
    return val_loss, val_accuracy

# Define the testing loop
def test(model, device, test_loader, criterion):
    model.eval()
    test_loss = 0
    test_correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.permute(0, 3, 1, 2).to(device), target.to(device) # Permute dimensions
            output = model(data)
            test_loss += criterion(output, target).item()
            pred = output.argmax(dim=1, keepdim=True)
            test_correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    test_accuracy = 100. * test_correct / len(test_loader.dataset)
    return test_loss, test_accuracy

# Train and val the model
for epoch in range(10):
    train_loss, train_accuracy = train(model, device, train_loader, criterion, optimizer)
    val_loss, val_accuracy = validation(model, device, val_loader, criterion)
    print('Epoch: {} \tTrain Loss: {:.6f} \tTrain Accuracy: {:.2f}% \tVal Loss: {:.6f} \tVal Accuracy: {:.2f}%'.format(
        epoch+1, train_loss, train_accuracy, val_loss, val_accuracy))

# Evaluate the model on the test set
test_loss, test_accuracy = test(model, device, test_loader, criterion)
print('Test Loss: {:.6f} \tTest Accuracy: {:.2f}%'.format(test_loss, test_accuracy))